config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "staticpages#top"
  get '/privacy', to: 'staticpages#privacy'
  devise_for :users
  post '/guest_login', to: 'guest_users#create'
  delete 'guest_logout', to: 'guest_users#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :birds, only: %i[index]
  resources :pets, only: %i[create show destroy] do
    get 'speak', on: :member
  end

  resources :rooms, only: %i[index show] do
    resources :pet_chat_in_rooms, only: [:create]
  end

  resource :mypage, only: %i[show]
  get 'show_my_pet' => "mypages#show_my_pet"
  get 'show_fav_pet' => "mypages#show_fav_pet"
  resource :profile, only: %i[show edit update]
  resources :vocabs, only: %i[create]
  resources :favorites, only: %i[create destroy]
  resources :pet_in_rooms, only: %i[create destroy]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: %i[show edit update]
  before_action :set_user, only: %i[show edit update]

  def show
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      redirect_to mypage_path, success: 'プロフィールを更新しました。'
    else
      flash.now[:danger] = 'プロフィールの更新に失敗しました。'
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def profile_params
    params.require(:user).permit(:name, :email)
  end
end

app/views/profiles/_pet.html.erb
<div class="card card-compact w-96 bg-base-100 shadow-xl">
  <figure><%= image_tag pet.bird.bird_image_url, class: 'card-img-top', size: '300x200' %></figure>
  <div class="card-body">
    <h2 class="card-title"><%= pet.name %></h2>
    <div class="card-actions justify-end">
      <button class="btn btn-primary"><%= link_to "様子を見る", pet_path(pet) %></button>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="mb-6 text-center">
  <span class="text-3xl font-bold">
    <h1><%= "プロフィールの編集" %></h1>
  </span>
</div>

<div class='flex flex-wrap justify-center mb-6'>
  <%= form_with model: @user, url: profile_path, html: { class: 'w-11/12 md:w-10/12 xl:w-8/12' }, data: { turbo_method: false } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="mb-6">
      <%= f.label :name, class: 'mb-2 block text-sm text-gray-600' %>
      <%= f.text_field :name, class: 'w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100' %>
    </div>
    <div class="mb-6">
      <%= f.label :email, class: 'mb-2 block text-sm text-gray-600' %>
      <%= f.email_field :email, class: 'w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100' %>
    </div>
    <p><%= f.submit "更新", class: 'inline-flex w-full items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none cursor-pointer' %></p>
  <% end %>
</div>

<div class="text-center">
  <%= link_to "戻る", mypage_path %>
</div>

app/views/profiles/show.html.erb
<div class="bg-gray-800 h-screen">
  <div class="container mx-auto sm:w-11/12 lg:w-11/12">
    <div class="container pt-3">
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <h1 class="float-left mb-5 text-gray-300"><%= "プロフィール" %></h1>
          <%= link_to "プロフィールの編集", edit_profile_path, class: 'btn btn-success float-right text-gray-100' %>
          <table class="table text-gray-300">
            <tr>
              <th scope="row" ><%= "名前" %></th>
              <td><%= current_user.name %></td>
            </tr>
            <tr>
              <th scope="row"><%= "Eメール" %></th>
              <td><%= current_user.email %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>