config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "staticpages#top"
  get '/privacy', to: 'staticpages#privacy'
  devise_for :users
  post '/guest_login', to: 'guest_users#create'
  delete 'guest_logout', to: 'guest_users#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :birds, only: %i[index]
  resources :pets, only: %i[create show destroy] do
    get 'speak', on: :member
  end

  resources :rooms, only: %i[index show] do
    resources :pet_chat_in_rooms, only: [:create]
  end

  resource :mypage, only: %i[show]
  get 'show_my_pet' => "mypages#show_my_pet"
  get 'show_fav_pet' => "mypages#show_fav_pet"
  resource :profile, only: %i[show edit update]
  resources :vocabs, only: %i[create]
  resources :favorites, only: %i[create destroy]
  resources :pet_in_rooms, only: %i[create destroy]
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :bird
  has_many :vocabs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :pet_in_rooms, dependent: :destroy
  has_many :pet_chat_in_rooms, dependent: :destroy

  validates :name, length: { maximum: 255 }, presence: true

  def enter(room, place)
    pet_in_rooms.create(room_id: room.id, place: place)
  end

  def exit(room)
    pet_in_rooms.find_by(room_id: room.id, pet_id: self.id).destroy
  end

  def enter?(room)
    pet_in_rooms.exists?(room_id: room.id)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :set_pet, only: %i[destroy]

  def show
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = current_user.pets.build(pet_params)
    if @pet.save
      redirect_to mypage_path, success: '新しいペットをお迎えしました！'
    else
      redirect_to birds_path, danger: 'ペットをお迎えに失敗しました。'
    end
  end

  def destroy
    @pet.destroy!

    respond_to do |format|
      format.turbo_stream
    end
  end

  def speak
    pet = Pet.find(params[:id])
    vocabs = pet.vocabs.order(frequency: :desc).limit(10)
    render json: { vocabs: vocabs.map(&:word) }
  end

  private

  def set_pet
    @pet = current_user.pets.find(params[:id])
  end

  def pet_params
    params.permit(:name).merge(bird_id: params[:bird_id])
  end
end

app/views/pets/_favorite.html.erb
<%= link_to favorites_path(pet_id: pet.id), 
            id: "favorite-button-for-pet-#{pet.id}",
            data: { turbo_method: :post } do %>
  <i class="fa-regular fa-star fa-2xl" style="color: #ffffff;"></i>
<% end %>

app/views/pets/_favorite_button.html.erb
<% if user_signed_in? %>
  <% if current_user.favorite?(pet) %>
    <%= render 'pets/unfavorite', { pet: pet } %>
  <% else %>
    <%= render 'pets/favorite', { pet: pet } %>
  <% end %>
<% end %>

app/views/pets/_pet.html.erb
<div class="card card-compact w-96 bg-base-100 shadow-xl p-10">
  <figure><%= image_tag pet.bird.bird_image_url, class: 'card-img-top', size: '300x200' %></figure>
  <div class="card-body">
    <h2 class="card-title"><%= pet.name %></h2>
    <h2 class="card-title"><%= "飼い主: #{pet.user.name}" %></h2>
    <div class="card-actions justify-end">
      <%= render 'pets/favorite_button', { pet: pet } %>
      <%= link_to "様子を見る", pet_path(pet), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/pets/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(pet_id: pet.id)),
            id: "unfavorite-button-for-pet-#{pet.id}",
            data: { turbo_method: :delete } do %>
  <i class="fa-solid fa-star fa-2xl" style="color: #FFD43B;"></i>
<% end %>

app/views/pets/destroy.turbo_stream.erb
<%= turbo_stream.remove "pet_#{@pet.id}" %>
<%= turbo_stream.remove "pet_#{@pet.id}" %>

<%= turbo_stream.replace "show_pet_area" do %>
  <%= turbo_frame_tag "show_pet_area" %>
<% end %>

app/views/pets/show.html.erb
<div data-controller="talk-to-bird" data-talk-to-bird-pet-id="<%= @pet.id %>">
  <div data-controller="bird-speak" data-bird-speak-pet-id="<%= @pet.id %>">
    <div class="bg-base-300 h-screen">
      <div class="container mx-auto md:w-12/12 lg:w-10/12 pt-10">
        <div class="grid grid-cols-12 gap-3">
          <div class="col-span-3">
            <h2 class="card-title"><%= @pet.name %></h2>
            <h2 class="card-title"><%= "飼い主: #{@pet.user.name}" %></h2>
            <%= render 'favorite_button', { pet: @pet } %>
            <div><%= link_to "戻る", root_path, class: "btn btn-primary" %></div>
            <div><button data-action="click->bird-speak#birdSpeak" data-bird-speak-target="birdSpeakBtn" class="btn btn-primary">聞いてみる（テキスト）</button></div>
          </div>
          <div class="col-span-9">
            <%= image_tag @pet.bird.bird_image_url %>
          </div>
          <div class="col-span-3">
            <% if user_signed_in? && current_user.own?(@pet) %>
              <button data-action="click->talk-to-bird#startStop" data-talk-to-bird-target="startStopBtn" class="btn btn-primary">話しかける</button>
            <% end %>
          </div>
          <div class="col-span-9">
            <div data-talk-to-bird-target="transcript"></div>
            <div data-bird-speak-target="birdsaid"></div>
            <% if user_signed_in? && current_user.own?(@pet) %>
              <button data-action="click->talk-to-bird#reset" data-talk-to-bird-target="resetBtn" class="btn btn-primary float-right">話しかけるのを中断する</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>