config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "staticpages#top"
  get '/privacy', to: 'staticpages#privacy'
  devise_for :users
  post '/guest_login', to: 'guest_users#create'
  delete 'guest_logout', to: 'guest_users#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :birds, only: %i[index]
  resources :pets, only: %i[create show destroy] do
    get 'speak', on: :member
  end

  resources :rooms, only: %i[index show] do
    resources :pet_chat_in_rooms, only: [:create]
  end

  resource :mypage, only: %i[show]
  get 'show_my_pet' => "mypages#show_my_pet"
  get 'show_fav_pet' => "mypages#show_fav_pet"
  resource :profile, only: %i[show edit update]
  resources :vocabs, only: %i[create]
  resources :favorites, only: %i[create destroy]
  resources :pet_in_rooms, only: %i[create destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bird.rb
class Bird < ApplicationRecord
  mount_uploader :bird_image, BirdImageUploader
  has_many :pets, dependent: :destroy

  enum bird_type: { normal: 0, opaline: 1, rainbow: 2 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :pet

  validates :user_id, uniqueness: { scope: :pet_id }
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :bird
  has_many :vocabs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :pet_in_rooms, dependent: :destroy
  has_many :pet_chat_in_rooms, dependent: :destroy

  validates :name, length: { maximum: 255 }, presence: true

  def enter(room, place)
    pet_in_rooms.create(room_id: room.id, place: place)
  end

  def exit(room)
    pet_in_rooms.find_by(room_id: room.id, pet_id: self.id).destroy
  end

  def enter?(room)
    pet_in_rooms.exists?(room_id: room.id)
  end
end

app/models/pet_chat_in_room.rb
class PetChatInRoom < ApplicationRecord
  belongs_to :room
  belongs_to :pet
end

app/models/pet_in_room.rb
class PetInRoom < ApplicationRecord
  belongs_to :pet
  belongs_to :room

  validates :pet_id, uniqueness: { scope: :room_id }
end

app/models/room.rb
class Room < ApplicationRecord
    mount_uploader :room_image, RoomImageUploader
    
    has_many :pet_in_rooms, dependent: :destroy
    has_many :pet_chat_in_rooms, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pets, through: :favorites, source: :pet

  validates :name, length: { maximum: 255 }, presence: true
  validates :email, presence: true, uniqueness: true
  validates :role, presence: true

  enum role: { general: 0, admin: 1, guest: 2 }

  def own?(object)
    self.id == object.user_id
  end

  def favorite(pet)
    favorite_pets << pet
  end

  def unfavorite(pet)
    favorite_pets.destroy(pet)
  end

  def favorite?(pet)
    favorite_pets.include?(pet)
  end
end

app/models/user_having_bird.rb
class UserHavingBird < ApplicationRecord
  belongs_to :user
  belongs_to :bird
end

app/models/vocab.rb
class Vocab < ApplicationRecord
  belongs_to :pet

  def increase_frequency
    self.frequency += 1
    save
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :pet

  def increase_frequency
    self.frequency += 1
    save
  end
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  def index
    @birds = Bird.all
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @pet = Pet.find(params[:pet_id])
    current_user.favorite(@pet)
  end
  
  def destroy
    @pet = current_user.favorites.find(params[:id]).pet
    current_user.unfavorite(@pet)
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def show
    @my_pets = current_user.pets
    @favorite_pets = current_user.favorite_pets.includes(:user).order(created_at: :desc)
  end

  def show_my_pet
    @pet = current_user.pets.find(params[:id])
  end

  def show_fav_pet
    @pet = current_user.favorite_pets.find(params[:id])
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :set_pet, only: %i[destroy]

  def show
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = current_user.pets.build(pet_params)
    if @pet.save
      redirect_to mypage_path, success: '新しいペットをお迎えしました！'
    else
      redirect_to birds_path, danger: 'ペットをお迎えに失敗しました。'
    end
  end

  def destroy
    @pet.destroy!

    respond_to do |format|
      format.turbo_stream
    end
  end

  def speak
    pet = Pet.find(params[:id])
    vocabs = pet.vocabs.order(frequency: :desc).limit(10)
    render json: { vocabs: vocabs.map(&:word) }
  end

  private

  def set_pet
    @pet = current_user.pets.find(params[:id])
  end

  def pet_params
    params.permit(:name).merge(bird_id: params[:bird_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: %i[show edit update]
  before_action :set_user, only: %i[show edit update]

  def show
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      redirect_to mypage_path, success: 'プロフィールを更新しました。'
    else
      flash.now[:danger] = 'プロフィールの更新に失敗しました。'
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def profile_params
    params.require(:user).permit(:name, :email)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @pet_chats_in_room = PetChatInRoom.where(room_id: params[:id])
    @pets_in_room = PetInRoom.where(room_id: params[:id])
    @places = @pets_in_room.map { |pet_in_room| pet_in_room.place }
  end
end

app/controllers/vocabs_controller.rb
class VocabsController < ApplicationController
  before_action :authenticate_user!, only: %i[create]

  def create
    text = params[:vocab][:text]
    api_key = ENV.fetch('GOO_LAB_API_KEY')
    analysis_result = MorphologicalAnalysisService.analyze(text, api_key)
    vocabs_array = analysis_result['word_list'].flatten(1)
    vocabs_array.delete(["空白", ""])
    learned_vocabs = Pet.find(params[:vocab][:pet_id]).vocabs

    vocabs_array.each do |new_vocab|
      @vocab = Vocab.new(pet_id: params[:vocab][:pet_id], word: new_vocab[1], pos: new_vocab[0])
      vocab_or_nil = learned_vocabs.find_by(word: @vocab.word, pos: @vocab.pos)

      if vocab_or_nil === nil
        @vocab.save
      else
        vocab_or_nil.increase_frequency
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/budgies/create.html.erb
<h1>Budgies#create</h1>
<p>Find me in app/views/budgies/create.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="p-4 mb-4 text-md text-gray-100 text-center font-bold 
              <%= "bg-green-800" if message_type == "notice" %>
              <%= "bg-green-800" if message_type == "success" %>
              <%= "bg-red-800" if message_type == "alert" %>
              <%= "bg-red-800" if message_type == "danger" %>"
  ><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-base-100 text-base-content rounded">
  <nav class="grid grid-flow-col gap-4">
    <a class="link link-hover">利用規約</a>
    <%= link_to 'プライバシーポリシー', privacy_path, class: 'link link-hover' %>
    <a class="link link-hover">お問い合わせ</a>
    <p>Copyright © 2024 おしゃべりインコ</p>
  </nav> 
  <div class="w-32">
    <a href="http://www.goo.ne.jp/">
      <img src="//u.xgoo.jp/img/sgoo.png" alt="supported by goo" title="supported by goo">
    </a>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="drawer sticky top-0 z-50">
  <input id="my-drawer-3" type="checkbox" class="drawer-toggle" /> 
  <div class="drawer-content flex flex-col">
    <!-- Navbar -->
    <div class="w-full navbar bg-base-100">
      <div class="flex-none lg:hidden">
        <label for="my-drawer-3" aria-label="open sidebar" class="btn btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </label>
      </div> 
      <div class="flex-1 px-2 mx-2"><%= link_to "おしゃべりインコ", root_path %></div>
      <div class="flex-none hidden lg:block">
        <ul class="menu menu-horizontal">
          <!-- Navbar menu content here -->
          <li><%= link_to "交流スペース", rooms_path %></li>
          <li><%= link_to "インコをお迎えする", birds_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "MYインコ", mypage_path, data: { turbo: false } %></li>
            <li>
              <div class="dropdown dropdown-end">
                <i tabindex="0" role="button" class="fas fa-user-circle fa-xl text-blue-500"></i>
                <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 mt-32">
                  <li><%= link_to "プロフィール", profile_path %></li>
                  <li>
                    <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } unless current_user.guest? %>
                    <%= link_to "ログアウト", guest_logout_path, data: { turbo_method: :delete } if current_user.guest? %>
                  </li>
                </ul>
              </div>
            </li>
          <% else %>
            <li>
              <div class="dropdown dropdown-end">
                <i tabindex="0" role="button" class="fas fa-user-circle fa-xl text-blue-500"></i>
                <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52 mt-32">
                  <li><%= link_to "新規登録", new_user_registration_path %></li>
                  <li><%= link_to "ログイン", new_user_session_path %></li>
                </ul>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div> 
  <div class="drawer-side">
    <label for="my-drawer-3" aria-label="close sidebar" class="drawer-overlay"></label> 
    <ul class="menu p-4 w-80 min-h-full bg-base-100">
      <!-- Sidebar content here -->
      <li><%= link_to "交流スペース", rooms_path %></li>
      <li><%= link_to "インコをお迎えする", birds_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "MYインコ", mypage_path %></li>
        <li><%= link_to "プロフィール", profile_path %></li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } unless current_user.guest? %>
          <%= link_to "ログアウト", guest_logout_path, data: { turbo_method: :delete } if current_user.guest? %>
        </li>
      <% else %>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>