config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: "staticpages#top"
  get '/privacy', to: 'staticpages#privacy'
  devise_for :users
  post '/guest_login', to: 'guest_users#create'
  delete 'guest_logout', to: 'guest_users#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :birds, only: %i[index]
  resources :pets, only: %i[create show destroy] do
    get 'speak', on: :member
  end

  resources :rooms, only: %i[index show] do
    resources :pet_chat_in_rooms, only: [:create]
  end

  resource :mypage, only: %i[show]
  get 'show_my_pet' => "mypages#show_my_pet"
  get 'show_fav_pet' => "mypages#show_fav_pet"
  resource :profile, only: %i[show edit update]
  resources :vocabs, only: %i[create]
  resources :favorites, only: %i[create destroy]
  resources :pet_in_rooms, only: %i[create destroy]
end

app/models/room.rb
class Room < ApplicationRecord
    mount_uploader :room_image, RoomImageUploader
    
    has_many :pet_in_rooms, dependent: :destroy
    has_many :pet_chat_in_rooms, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @pet_chats_in_room = PetChatInRoom.where(room_id: params[:id])
    @pets_in_room = PetInRoom.where(room_id: params[:id])
    @places = @pets_in_room.map { |pet_in_room| pet_in_room.place }
  end
end

app/views/rooms/_enter.html.erb
<%= link_to pet_in_rooms_path(pet_id: pet.id, room_id: room.id),
            id: "enter-button-for-pet-#{pet.id}",
            class: "float-right",
            data: { turbo_method: :post } do %>
  <div class="card-actions justify-end">
    <button class="btn btn-primary">
      放鳥する
    </button>
  </div>
<% end %>

app/views/rooms/_exchange_button.html.erb
<% if user_signed_in? %>
  <% if pet.enter?(room) %>
    <%= render 'exit', { pet: pet, room: room } %>
  <% else %>
    <%= render 'enter', { pet: pet, room: room } %>
  <% end %>
<% end %>

app/views/rooms/_exit.html.erb
<%= link_to pet_in_room_path(room.pet_in_rooms.find_by(pet_id: pet.id), room_id: room.id),
            id: "exit-button-for-pet-#{pet.id}",
            class: "float-right",
            data: { turbo_method: :delete } do %>
  <div class="card-actions justify-end">
    <button class="btn btn-accent">
      回収する
    </button>
  </div>
<% end %>

app/views/rooms/_pet.html.erb
<div class="w-54 h-20 bg-red-100 hover:bg-red-200 text-black">
  <div class="flex grid grid-cols-12">
    <figure class="col-span-4"><%= image_tag pet.bird.bird_image_url, size: '90x60' %></figure>
    <h2 class="col-span-7 mt-3"><%= pet.name %></h2>
    <div class="col-end-13">
      <%= render partial: 'exchange_button', locals: { pet: pet, room: room } %>
    </div>
  </div>
</div>

app/views/rooms/_pet_in_room.html.erb
<%= turbo_frame_tag dom_id(pet) do %>
  <div data-controller="bird-speak" data-bird-speak-pet-id="<%= pet.id %>">
    <div class="w-72 h-36 text-white">
      <h2 class="ml-12"><%= pet.name %></h2>
      <figure><%= image_tag pet.bird.bird_image_url, size: '100x70' %></figure>
      <div data-bird-speak-target="birdsaid"></div>
    </div>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div class="card card-compact w-96 bg-base-100 shadow-xl p-10">
  <figure><%= image_tag room.room_image_url, class: 'card-img-top', size: '300x200' %></figure>
  <div class="card-body">
    <h2 class="card-title"><%= room.name %></h2>
    <h2 class="card-title"><%= "最大#{room.entry_limit}人" %></h2>
    <div class="card-actions justify-end">
      <button class="btn btn-primary"><%= link_to "部屋に入る", room_path(room) %></button>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="bg-base-300 min-h-screen">
  <div class="container mx-auto sm:w-11/12 lg:w-11/12">
    <div class="grid sm:grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 mt-3 mb-3">
      <% @rooms.each do |room| %>
        <%= render 'room', { room: room } %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="bg-base-300 min-h-screen">
  <div class="container mx-auto sm:w-11/12 lg:w-11/12">
    <div class="grid grid-cols-12 gap-3 mt-3 min-h-screen">

      <div class="col-span-3">
        <% if user_signed_in? %>
          <% current_user.pets.each do |pet| %>
            <%= render 'pet', { pet: pet, room: @room} %>
          <% end %>
        <% end %>
      </div>

      <div class="col-span-9 relative">
        <div class="absolute">
          <div id="steady-pets-in-room-1">
            <%= render 'pet_in_room', { pet: @pets_in_room.find_by(place: 1).pet, room: @room } if @places.include?(1) %>
          </div>
        </div>
        <div class="absolute mt-32">
          <div id="steady-pets-in-room-2">
            <%= render 'pet_in_room', { pet: @pets_in_room.find_by(place: 2).pet, room: @room } if @places.include?(2) %>
          </div>
        </div>
        <div class="absolute mt-64">
          <div id="steady-pets-in-room-3">
            <%= render 'pet_in_room', { pet: @pets_in_room.find_by(place: 3).pet, room: @room } if @places.include?(3) %>
          </div>
        </div>
        <div class="absolute mt-96">
          <div id="steady-pets-in-room-4">
            <%= render 'pet_in_room', { pet: @pets_in_room.find_by(place: 4).pet, room: @room } if @places.include?(4) %>
          </div>
        </div>
        <div class="absolute mt-32 ml-72">
          <div id="steady-pets-in-room-5">
            <%= render 'pet_in_room', { pet: @pets_in_room.find_by(place: 5).pet, room: @room } if @places.include?(5) %>
          </div>
        </div>
        <div class="absolute mt-96 ml-72">
          <div id="steady-pets-in-room-6">
            <%= render 'pet_in_room', { pet: @pets_in_room.find_by(place: 6).pet, room: @room } if @places.include?(6) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>